[module]
  [module.hugoVersion]
    min = "0.126.0"

[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js"]

[outputFormats]
  [outputFormats.print]
    name= "print"
    baseName = "index.print"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

[params.relearn.dependencies]
  [params.relearn.dependencies.mathjax]
    name = "MathJax"
  [params.relearn.dependencies.mermaid]
    name = "Mermaid"
  [params.relearn.dependencies.openapi]
    name = "OpenApi"
